using System.Diagnostics;
using System.Text;

namespace StaticDictionaries.SourceGeneration;

public static class SourceGenerationHelper
{
    private const string Header = @"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the StaticDictionaries source generator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable";

    public static string GenerateExtensionClass(StringBuilder sb, EnumDictionaryToGenerate dictionaryToGenerate)
    {
        // Debugger.Launch();
        
        sb
            .Append(Header)
            .Append(@"
using System;

");
        if (!string.IsNullOrEmpty(dictionaryToGenerate.Namespace))
        {
            sb.Append(@"
namespace ").Append(dictionaryToGenerate.Namespace).Append(@"
{");
        }

        sb.Append(@"
    ").Append(dictionaryToGenerate.IsPublic ? "public" : "internal").Append(@" static partial class ").Append($"{dictionaryToGenerate.Name}Extensions").Append(@"
    {
        /// <summary>
        /// The number of members in the enum.
        /// This is a non-distinct count of defined names.
        /// </summary>
        public const int Length = ").Append(dictionaryToGenerate.Members.Count).Append(";");

        sb.AppendLine();

        int i = 0;
        foreach (string propertyName in dictionaryToGenerate.PropertyNames)
        {
            Type type = dictionaryToGenerate.PropertyTypes[i];

            string wrapper = GetWrapperByType(type);

            sb.AppendLine(@$"public static {type.Name} {propertyName}(this {dictionaryToGenerate.Name} member)");
            sb.Append("{");
            sb.AppendLine();
            sb.Append(@" return member switch {");
            sb.AppendLine();

            foreach ((string MemberName, object value) property in dictionaryToGenerate.Members.Select(x => (x.MemberName, x.Values[i]!)))
            {
                string propertyValueString = GetPropertyValueString(property.value, type);

                sb.Append($"{dictionaryToGenerate.Name}.{property.MemberName} => {wrapper}{propertyValueString}{wrapper},");
                sb.AppendLine();
            }

            sb.Append("_ => ");
            sb.Append("throw new NotSupportedException() ");
            sb.AppendLine();
            sb.Append("};");
            sb.AppendLine();
            sb.Append("}");
            sb.AppendLine();
            sb.AppendLine();

            i++;
        }

        sb.AppendLine();

//         foreach (EnumPropertyDefinition property in dictionaryToGenerate.Properties)
//         {
//             sb.Append(@"").Append(property.Id);
//             sb.Append(" => ");
//             sb.Append('"').Append(dictionaryToGenerate.FullyQualifiedName).Append(@""",");
//         }
//
//         sb.AppendLine(@$"public static {dictionaryToGenerate.FullyQualifiedName} GetById(int id)");
//         sb.Append(@" => value switch {");
//
//         foreach (EnumPropertyDefinition property in dictionaryToGenerate.Properties)
//         {
//             sb.Append(@"").Append(property.Id);
//             sb.Append(" => ");
//             sb.Append('"').Append(dictionaryToGenerate.FullyQualifiedName).Append(@""",");
//         }
//         sb.Append("}");
//
//         sb.Append(@"
//         public static string[] GetNames()
//         {
//             return new[]
//             {");
//         foreach (EnumPropertyDefinition property in dictionaryToGenerate.Properties)
//         {
//             sb.Append(@"nameof(").Append(dictionaryToGenerate.FullyQualifiedName).Append('.').Append(property.PropertyName).Append("),");
//         }
//
        sb.Append(@"
    }");
        if (!string.IsNullOrEmpty(dictionaryToGenerate.Namespace))
        {
            sb.Append(@"
}");
        }

        return sb.ToString();
    }

    private static string GetWrapperByType(Type type)
    {
        if (type == typeof(string))
        {
            return "\"";
        }

        return string.Empty;
    }

    private static string GetPropertyValueString(object value, Type type)
    {
        if (type == typeof(bool))
        {
            return value.ToString().ToLower();
        }

        return value.ToString();
    }
}